### ISSUE TITLE
recreate方法更新主题导致动画失效

### ISSUE THREAD

**Issue by ijkzen** [Ifxcyr/RippleAnimation#3]
您好，您的项目对我帮助很大。但是这种方法仍然有一些局限性，因为它是与Activity相关的，如果是使用recreate方法去更新主题，添加到根布局的View就会消失，因此动画也会消失；我考虑使用一种与Activity无关的方法，就是添加一个全屏的悬浮窗，然后在悬浮窗内执行动画；但是这个方案要对不同版本的操作系统和手机进行悬浮窗权限的适配，成本有点太高了；所以想请问一下，您是否有更好的解决方案？

**Comment by wuyr** [comment]
您好，可以使用无需recreate的主题切换方案，比如: [Android-skin-support
](https://github.com/ximsfei/Android-skin-support)，[Android-Skin-Loader
](https://github.com/fengjundev/Android-Skin-Loader)这些，都是可以直接生效，不用recreate的

**Comment by ijkzen** [comment]
好的，我会去了解这些换肤库，感谢您的帮助
